theme: minima
header_pages:
  - dogs.md
  - about.md
show_excerpts: true
skin: dark
minima:
  social_links:
    twitter: jekyllrb
    github: jekyll
    stackoverflow: "11111"
    dribbble: jekyll
    facebook: jekyll
