remote_theme: jekyll/minima
#remote-theme: pages-themes/tactile@v0.2.0
header_pages:
  - blog.html
  - dogs.md
  - litters.md
  - breed.md
  - about.md
show_excerpts: true
title: greenfallow labradors
minima:
  paginate: 3
  paginate_path: "/page:num/"    
plugins:
 - jekyll-paginate
