remote_theme: jekyll/minima
header_pages:
  - blog.md
  - dogs.md
  - breed.md
  - about.md
show_excerpts: true
minima:
  social_links:
    facebook: bernd.grunefeld.5
paginate: 3
paginate_path: "/blog/page:num/"    
plugins:
 - jekyll-paginate
