remote_theme: jekyll/minima
header_pages:
  - blog.md
  - dogs.md
  - breed.md
  - about.md
show_excerpts: true
minima:
  paginate: 3
  paginate_path: "/_posts/page:num/"
  social_links:
    facebook: bernd.grunefeld.5
